# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lock_windows.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from Lock_timer import CountdownTimer


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Lock_ui = QtWidgets.QFrame(self.centralwidget)
        self.Lock_ui.setGeometry(QtCore.QRect(0, -10, 1920, 1080))
        self.Lock_ui.setStyleSheet("QFrame#Lock_ui{\n"
"    \n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"")
        # 修改为正确的 PySide6 语法
        self.Lock_ui.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Lock_ui.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Lock_ui.setObjectName("Lock_ui")
        self.frame_6 = QtWidgets.QFrame(self.Lock_ui)
        self.frame_6.setGeometry(QtCore.QRect(230, 170, 1161, 461))
        self.frame_6.setStyleSheet("QFrame{;border-radius:12px;background-color: rgb(0, 0, 0);}\n"
"\n"
"")
        # 修改为正确的 PySide6 语法
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_24 = QtWidgets.QLabel(self.frame_6)
        self.label_24.setGeometry(QtCore.QRect(400, 142, 101, 41))
        self.label_24.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_24.setObjectName("label_24")
        self.timer_show = CountdownTimer(self.frame_6)
        self.timer_show.setGeometry(QtCore.QRect(20, 20, 1121, 421))
        self.timer_show.setObjectName("timer_show")
        self.warning = QtWidgets.QFrame(self.Lock_ui)
        self.warning.setGeometry(QtCore.QRect(310, -220, 471, 221))
        self.warning.setStyleSheet("QFrame#warning{border-radius:12px; border: 2px solid #e0e0e0; background-color: rgb(252, 252, 252);\n"
"}\n"
"\n"
"")
        # 修改为正确的 PySide6 语法
        self.warning.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warning.setObjectName("warning")
        self.label_20 = QtWidgets.QLabel(self.warning)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 181, 23))
        self.label_20.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_20.setObjectName("label_20")
        self.widget = QtWidgets.QWidget(self.warning)
        self.widget.setGeometry(QtCore.QRect(0, 160, 471, 61))
        self.widget.setStyleSheet("QWidget{background-color: rgb(243, 243, 243);border-radius:12px;}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 16, 171, 31))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{border-radius:12px;\n"
"    background-color: rgb(79, 209, 197);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_3:hover{\n"
"    \n"
"    background-color: rgb(72, 191, 179);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 16, 171, 31))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{border-radius:12px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_3:hover{\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_21 = QtWidgets.QLabel(self.warning)
        self.label_21.setGeometry(QtCore.QRect(20, 50, 381, 41))
        self.label_21.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_21.setObjectName("label_21")
        self.label = QtWidgets.QLabel(self.Lock_ui)
        self.label.setGeometry(QtCore.QRect(750, 110, 198, 31))
        self.label.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";\n"
"color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.Lock_ui)
        self.pushButton.setGeometry(QtCore.QRect(30, 720, 221, 61))
        self.pushButton.setObjectName("pushButton")

        self.label_2 = QtWidgets.QLabel(self.Lock_ui)
        self.label_2.setGeometry(QtCore.QRect(750, 640, 198, 31))
        self.label_2.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";\n"
"color:rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_24.setText(_translate("MainWindow", "Focus time:"))
        self.label_20.setText(_translate("MainWindow", "Confirm Task Deletion"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.label_21.setText(_translate("MainWindow", "Are you sure to delete task,This action cannot be undone"))
        self.label.setText(_translate("MainWindow", "正在执行任务"))
        self.pushButton.setText(_translate("MainWindow", "提前结束"))
