# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lock_ui.ui'
#
# Created by: PySide6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again. Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

# 将 UI 布局类更名为 Ui_Lock_Window
class Ui_Lock_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1241, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Lock_ui = QtWidgets.QFrame(self.centralwidget)
        self.Lock_ui.setGeometry(QtCore.QRect(0, -10, 1241, 771))
        self.Lock_ui.setStyleSheet("QFrame#Lock_ui{background-color: rgb(248, 249, 250);\n"
"}\n"
"")
        self.Lock_ui.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Lock_ui.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Lock_ui.setObjectName("Lock_ui")
        self.label_6 = QtWidgets.QLabel(self.Lock_ui)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 198, 23))
        self.label_6.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";")
        self.label_6.setObjectName("label_6")
        self.frame_6 = QtWidgets.QFrame(self.Lock_ui)
        self.frame_6.setGeometry(QtCore.QRect(40, 70, 1161, 461))
        self.frame_6.setStyleSheet("QFrame{background-color: rgb(255, 255, 255);border-radius:12px;}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 181, 23))
        self.label_19.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_19.setObjectName("label_19")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 400, 131, 41))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{border-radius:12px;\n"
"    background-color: rgb(79, 209, 197);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_2:hover{\n"
"    \n"
"    background-color: rgb(72, 191, 179);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_24 = QtWidgets.QLabel(self.frame_6)
        self.label_24.setGeometry(QtCore.QRect(400, 142, 101, 41))
        self.label_24.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_24.setObjectName("label_24")
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_6)
        self.timeEdit.setGeometry(QtCore.QRect(480, 150, 351, 31))
        self.timeEdit.setStyleSheet("/* 修复 QTimeEdit 样式 - 保留功能按钮 */\n"
"QTimeEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"    font: 700 9pt \"Microsoft YaHei UI\";\n"
"    background-color: transparent;  /* 保持背景透明 */\n"
"}\n"
"\n"
"QTimeEdit:focus {\n"
"    border-bottom: 2px solid #45b7ac;\n"
"}\n"
"\n"
"/* 特别保护按钮区域 */\n"
"QTimeEdit::up-button, \n"
"QTimeEdit::down-button {\n"
"    width: 15px;  /* 按钮宽度 */\n"
"    subcontrol-: border;\n"
"    subcontrol-position: right center;  /* 按钮位置 */\n"
"}\n"
"\n"
"QTimeEdit::up-arrow, \n"
"QTimeEdit::down-arrow {\n"
"    width: 7px;  /* 箭头大小 */\n"
"    height: 7px;\n"
"}")
        self.timeEdit.setObjectName("timeEdit")
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setGeometry(QtCore.QRect(400, 190, 461, 41))
        self.label_25.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";color:rgb(203, 203, 203)")
        self.label_25.setObjectName("label_25")
        self.warning = QtWidgets.QFrame(self.Lock_ui)
        self.warning.setGeometry(QtCore.QRect(310, -220, 471, 221))
        self.warning.setStyleSheet("QFrame#warning{border-radius:12px; border: 2px solid #e0e0e0; background-color: rgb(252, 252, 252);\n"
"}\n"
"\n"
"")
        self.warning.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warning.setObjectName("warning")
        self.label_20 = QtWidgets.QLabel(self.warning)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 181, 23))
        self.label_20.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_20.setObjectName("label_20")
        self.widget = QtWidgets.QWidget(self.warning)
        self.widget.setGeometry(QtCore.QRect(0, 160, 471, 61))
        self.widget.setStyleSheet("QWidget{background-color: rgb(243, 243, 243);border-radius:12px;}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 16, 171, 31))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{border-radius:12px;\n"
"    background-color: rgb(79, 209, 197);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_3:hover{\n"
"    \n"
"    background-color: rgb(72, 191, 179);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 16, 171, 31))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{border-radius:12px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_3:hover{\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_21 = QtWidgets.QLabel(self.warning)
        self.label_21.setGeometry(QtCore.QRect(20, 50, 381, 41))
        self.label_21.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_21.setObjectName("label_21")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_shadows()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Focus Lock"))
        self.label_19.setText(_translate("MainWindow", "锁机"))
        self.pushButton_2.setText(_translate("MainWindow", "开始"))
        self.label_24.setText(_translate("MainWindow", "Focus time:"))
        self.label_25.setText(_translate("MainWindow", "提示：这个模式开启后将无法提前退出"))
        self.label_20.setText(_translate("MainWindow", "Confirm Task Deletion"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.label_21.setText(_translate("MainWindow", "Are you sure to delete task,This action cannot be undone"))
    def add_shadows(self):
        """为指定控件添加Windows 11风格的阴影"""
        # 需要添加阴影的控件列表
        shadow_widgets = [
            self.frame_6 # Dashboard 中的第一个卡片
           # Dashboard 中的第二个卡片

        ]

        # 为每个控件添加阴影
        for widget in shadow_widgets:
            shadow = QtWidgets.QGraphicsDropShadowEffect(widget)
            shadow.setBlurRadius(20)  # 阴影模糊半径
            shadow.setColor(QtGui.QColor(0, 0, 0, 30))  # 阴影颜色和透明度
            shadow.setOffset(0, 2)  # 阴影偏移量
            widget.setGraphicsEffect(shadow)

            # 确保控件有适当的边距，防止阴影被裁剪
            # widget.setAttribute(QtCore.Qt.WA_TranslucentBackground)
            if hasattr(widget, 'setContentsMargins'):
                widget.setContentsMargins(10, 10, 10, 10)


# 新增的封装类，用于将 UI 布局和功能结合
class Lock_Window(QtWidgets.QWidget, Ui_Lock_Window):
    def __init__(self, parent=None):
        super().__init__(parent)
        # 这里你可以选择是使用 setupUi 在自己身上，还是创建一个 QMainWindow
        # 因为在 Todo_ui.py 中你把它当成 QWidget 来用，所以这里也应该保持一致
        self.setupUi(self)