# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting_ui.ui'
#
# Created by: PySide6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again. Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

# UI 布局代码保持不变，但类名改为 Ui_Setting_Window
class Ui_Setting_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1241, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Setting_ui = QtWidgets.QFrame(self.centralwidget)
        self.Setting_ui.setGeometry(QtCore.QRect(0, -10, 1241, 771))
        self.Setting_ui.setStyleSheet("QFrame#Setting_ui{background-color: rgb(248, 249, 250);\n"
"}\n"
"")
        self.Setting_ui.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Setting_ui.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Setting_ui.setObjectName("Setting_ui")
        self.label_6 = QtWidgets.QLabel(self.Setting_ui)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 198, 23))
        self.label_6.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";")
        self.label_6.setObjectName("label_6")

        self.warning = QtWidgets.QFrame(self.Setting_ui)
        self.warning.setGeometry(QtCore.QRect(310, -220, 471, 221))
        self.warning.setStyleSheet("QFrame#warning{border-radius:12px; border: 2px solid #e0e0e0; background-color: rgb(252, 252, 252);\n"
"}\n"
"\n"
"")
        self.warning.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warning.setObjectName("warning")
        self.label_20 = QtWidgets.QLabel(self.warning)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 181, 23))
        self.label_20.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_20.setObjectName("label_20")
        self.widget = QtWidgets.QWidget(self.warning)
        self.widget.setGeometry(QtCore.QRect(0, 160, 471, 61))
        self.widget.setStyleSheet("QWidget{background-color: rgb(243, 243, 243);border-radius:12px;}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 16, 171, 31))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{border-radius:12px;\n"
"    background-color: rgb(79, 209, 197);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_3:hover{\n"
"    \n"
"    background-color: rgb(72, 191, 179);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 16, 171, 31))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{border-radius:12px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_3:hover{\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_21 = QtWidgets.QLabel(self.warning)
        self.label_21.setGeometry(QtCore.QRect(20, 50, 381, 41))
        self.label_21.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_21.setObjectName("label_21")
        self.Add = QtWidgets.QFrame(self.Setting_ui)
        self.Add.setGeometry(QtCore.QRect(400, -280, 471, 261))
        self.Add.setStyleSheet("QFrame#Add{border-radius:12px; border: 2px solid #e0e0e0; background-color: rgb(252, 252, 252);\n"
"}\n"
"\n"
"")
        self.Add.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Add.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Add.setObjectName("Add")
        self.label_22 = QtWidgets.QLabel(self.Add)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 181, 23))
        self.label_22.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_22.setObjectName("label_22")
        self.widget_2 = QtWidgets.QWidget(self.Add)
        self.widget_2.setGeometry(QtCore.QRect(0, 200, 471, 61))
        self.widget_2.setStyleSheet("QWidget{background-color: rgb(243, 243, 243);border-radius:12px;}\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.OK_Add = QtWidgets.QPushButton(self.widget_2)
        self.OK_Add.setGeometry(QtCore.QRect(40, 16, 171, 31))
        self.OK_Add.setStyleSheet("QPushButton#OK_Add{border-radius:12px;\n"
"    background-color: rgb(79, 209, 197);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#OK_Add:hover{\n"
"    \n"
"    background-color: rgb(72, 191, 179);\n"
"}\n"
"")
        self.OK_Add.setObjectName("OK_Add")
        self.Cancel_Add = QtWidgets.QPushButton(self.widget_2)
        self.Cancel_Add.setGeometry(QtCore.QRect(250, 16, 171, 31))
        self.Cancel_Add.setStyleSheet("QPushButton#Cancel_Add{border-radius:12px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#Cancel_Add:hover{\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
        self.Cancel_Add.setObjectName("Cancel_Add")
        self.label_23 = QtWidgets.QLabel(self.Add)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 101, 41))
        self.label_23.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_23.setObjectName("label_23")
        self.lineEdit = QtWidgets.QLineEdit(self.Add)
        self.lineEdit.setGeometry(QtCore.QRect(90, 57, 351, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;  /* 默认灰色下划线 */\n"
"    font: 700 9pt \"Microsoft YaHei UI\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #45b7ac;  /* 获得焦点时绿色下划线 */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_24 = QtWidgets.QLabel(self.Add)
        self.label_24.setGeometry(QtCore.QRect(10, 113, 101, 41))
        self.label_24.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_24.setObjectName("label_24")
        self.timeEdit = QtWidgets.QTimeEdit(self.Add)
        self.timeEdit.setGeometry(QtCore.QRect(90, 121, 351, 31))
        self.timeEdit.setStyleSheet("/* 修复 QTimeEdit 样式 - 保留功能按钮 */\n"
"QTimeEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"    font: 700 9pt \"Microsoft YaHei UI\";\n"
"    background-color: transparent;  /* 保持背景透明 */\n"
"}\n"
"\n"
"QTimeEdit:focus {\n"
"    border-bottom: 2px solid #45b7ac;\n"
"}\n"
"\n"
"/* 特别保护按钮区域 */\n"
"QTimeEdit::up-button, \n"
"QTimeEdit::down-button {\n"
"    width: 15px;  /* 按钮宽度 */\n"
"    subcontrol-: border;\n"
"    subcontrol-position: right center;  /* 按钮位置 */\n"
"}\n"
"\n"
"QTimeEdit::up-arrow, \n"
"QTimeEdit::down-arrow {\n"
"    width: 7px;  /* 箭头大小 */\n"
"    height: 7px;\n"
"}")
        self.timeEdit.setObjectName("timeEdit")



        self.frame_8 = QtWidgets.QFrame(self.Setting_ui)
        self.frame_8.setGeometry(QtCore.QRect(50,80,1161,61))
        self.frame_8.setStyleSheet("QFrame{background-color: rgb(255, 255, 255);border-radius:12px;}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_27 = QtWidgets.QLabel(self.frame_8)
        self.label_27.setGeometry(QtCore.QRect(20, 17, 271, 23))
        self.label_27.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_27.setObjectName("label_27")
        self.Open_Enable_Strict = QtWidgets.QPushButton(self.frame_8)
        self.Open_Enable_Strict.setGeometry(QtCore.QRect(1010, 15, 121, 31))
        self.Open_Enable_Strict.setStyleSheet("QPushButton#Open_Enable_Strict{border-radius:7px;\n"
"    background-color: rgb(79, 209, 197);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#Open_Enable_Strict:hover{\n"
"    \n"
"    background-color: rgb(72, 191, 179);\n"
"}\n"
"")
        self.Open_Enable_Strict.setObjectName("Open_Enable_Strict")
        self.label_28 = QtWidgets.QLabel(self.frame_8)
        self.label_28.setGeometry(QtCore.QRect(360, 20, 421, 23))
        self.label_28.setStyleSheet("font: 9pt \"Microsoft YaHei UI\";")
        self.label_28.setObjectName("label_28")
        self.textEditMotivation = QtWidgets.QTextEdit(self.Setting_ui)
        self.textEditMotivation.setGeometry(QtCore.QRect(50,170,1151,201))
        self.textEditMotivation.setStyleSheet("QTextEdit {\n"
"    background-color: #f8f9fa;\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}")
        self.textEditMotivation.setReadOnly(True)
        self.textEditMotivation.setObjectName("textEditMotivation")
        self.label_6.raise_()
        self.warning.raise_()
        self.Add.raise_()


        self.frame_8.raise_()
        self.textEditMotivation.raise_()
        self.add_shadows()


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Setting"))

        self.label_20.setText(_translate("MainWindow", "Confirm Task Deletion"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.label_21.setText(_translate("MainWindow", "Are you sure to delete task,This action cannot be undone"))
        self.label_22.setText(_translate("MainWindow", "Add Task"))
        self.OK_Add.setText(_translate("MainWindow", "OK"))
        self.Cancel_Add.setText(_translate("MainWindow", "Cancel"))
        self.label_23.setText(_translate("MainWindow", "Task name:"))
        self.label_24.setText(_translate("MainWindow", "Focus time:"))


        self.label_27.setText(_translate("MainWindow", "开启严格模式"))
        self.Open_Enable_Strict.setText(_translate("MainWindow", "Open"))
        self.label_28.setText(_translate("MainWindow", "提示：再打开这个模式后将无法提前结束"))
        self.textEditMotivation.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700; color:#2b8a3e;\">CheemsTips</span></h2>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-size:14px; color:#495057;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">技术限制并非绝对，但破解它们只会偷走你的时间 </li>\n"
"<li style=\" font-size:14px; color:#495057;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">此刻的「不自由」是未来自由的种子 </li>\n"
"<li style=\" font-size:14px; color:#495057;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">我们只拦截软件，但真正的敌人是分心的自己</li></ul>\n"
"<hr />\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#868e96;\">&quot;自律的痛轻如鸿毛，后悔的痛重若泰山&quot;</span></p></body></html>"))

    def add_shadows(self):
                """为指定控件添加Windows 11风格的阴影"""
                # 需要添加阴影的控件列表
                shadow_widgets = [
                        # Dashboard 中的第一个卡片


                        self.frame_8,

                        self.textEditMotivation,
                        # Dashboard 中的第二个卡片

                ]

                # 为每个控件添加阴影
                for widget in shadow_widgets:
                        shadow = QtWidgets.QGraphicsDropShadowEffect(widget)
                        shadow.setBlurRadius(20)  # 阴影模糊半径
                        shadow.setColor(QtGui.QColor(0, 0, 0, 30))  # 阴影颜色和透明度
                        shadow.setOffset(0, 2)  # 阴影偏移量
                        widget.setGraphicsEffect(shadow)

                        # 确保控件有适当的边距，防止阴影被裁剪
                        # widget.setAttribute(QtCore.Qt.WA_TranslucentBackground)
                        if hasattr(widget, 'setContentsMargins'):
                                widget.setContentsMargins(10, 10, 10, 10)