# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task_ui.ui'
#
# Created by: PySide6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Task_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1241, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Task_ui = QtWidgets.QFrame(self.centralwidget)
        self.Task_ui.setGeometry(QtCore.QRect(0, -10, 1241, 771))
        self.Task_ui.setStyleSheet("QFrame#Task_ui{background-color: rgb(248, 249, 250);\n"
                                   "}\n"
                                   "")
        self.Task_ui.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Task_ui.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Task_ui.setObjectName("Task_ui")
        self.label_6 = QtWidgets.QLabel(self.Task_ui)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 198, 23))
        self.label_6.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";")
        self.label_6.setObjectName("label_6")
        self.frame_6 = QtWidgets.QFrame(self.Task_ui)
        self.frame_6.setGeometry(QtCore.QRect(40, 70, 1161, 461))
        self.frame_6.setStyleSheet("QFrame{background-color: rgb(255, 255, 255);border-radius:12px;}\n"
                                   "")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 181, 23))
        self.label_19.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_19.setObjectName("label_19")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget.setGeometry(QtCore.QRect(20, 51, 1121, 341))
        self.tableWidget.setStyleSheet("/* 整体表格样式 */\n"
                                       "QTableWidget {\n"
                                       "     /* 浅灰色背景 */\n"
                                       "    gridline-color: transparent;\n"
                                       "    background-color: rgb(255, 255, 255);\n"
                                       "    border: 1px solid #e5e5e5;\n"
                                       "    border-radius: 4px;\n"
                                       "    gridline-color: #e5e5e5;\n"
                                       "    \n"
                                       "    font: 700 10pt \"Microsoft YaHei UI\";\n"
                                       "    font-size: 12px;\n"
                                       "    selection-background-color: #0078d4;  /* Windows 11选中色 */\n"
                                       "    selection-color: white;\n"
                                       "    outline: 0;  /* 移除选中时的虚线框 */\n"
                                       "}\n"
                                       "QTableView::item {\n"
                                       "   \n"
                                       "    border-right: none;  /* 隐藏竖线 */\n"
                                       "}\n"
                                       "/* 表头样式 */\n"
                                       "QHeaderView::section {\n"
                                       "    \n"
                                       "    color: rgb(160, 174, 192);\n"
                                       "    background-color: rgb(255, 255, 255);\n"
                                       "\n"
                                       "    border: none;\n"
                                       "    border-bottom: 1px solid #e5e5e5;\n"
                                       "    font-weight: 500;  /* 中等粗细 */\n"
                                       "    padding-left: 8px; \n"
                                       "    \n"
                                       "}\n"
                                       "\n"
                                       "/* 悬停效果 */\n"
                                       "QHeaderView::section:hover {\n"
                                       "    background-color: #edebe9;\n"
                                       "}\n"
                                       "\n"
                                       "/* 按下效果 */\n"
                                       "QHeaderView::section:pressed {\n"
                                       "    background-color: #e1dfdd;\n"
                                       "}\n"
                                       "\n"
                                       "/* 行交替颜色 */\n"
                                       "QTableWidget::item:alternate {\n"
                                       "    background-color: #faf9f8;\n"
                                       "}\n"
                                       "\n"
                                       "/* 单元格悬停效果 */\n"
                                       "QTableWidget::item:hover {\n"
                                       "    background-color: #f3f3f3;\n"
                                       "}\n"
                                       "\n"
                                       "/* 滚动条样式 */\n"
                                       "QScrollBar:vertical {\n"
                                       "    border: none;\n"
                                       "    background: #f3f3f3;\n"
                                       "    width: 10px;\n"
                                       "    margin: 0px 0px 0px 0px;\n"
                                       "}\n"
                                       "\n"
                                       "QScrollBar::handle:vertical {\n"
                                       "    background: #c4c4c4;\n"
                                       "    min-height: 20px;\n"
                                       "    border-radius: 5px;\n"
                                       "}\n"
                                       "\n"
                                       "QScrollBar::handle:vertical:hover {\n"
                                       "    background: #a0a0a0;\n"
                                       "}\n"
                                       "\n"
                                       "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
                                       "    background: none;\n"
                                       "}\n"
                                       "\n"
                                       "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                       "    background: none;\n"
                                       "}")
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)  # Changed row count to 0
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(279)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(39)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setGeometry(QtCore.QRect(1010, 406, 131, 41))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{border-radius:12px;\n"
                                        "    background-color: rgb(79, 209, 197);\n"
                                        "font: 700 10pt \"Microsoft YaHei UI\";}\n"
                                        "QPushButton#pushButton_2:hover{\n"
                                        "    \n"
                                        "    background-color: rgb(72, 191, 179);\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.warning = QtWidgets.QFrame(self.Task_ui)
        self.warning.setGeometry(QtCore.QRect(310, -220, 471, 221))
        self.warning.setStyleSheet(
            "QFrame#warning{border-radius:12px; border: 2px solid #e0e0e0; background-color: rgb(252, 252, 252);\n"
            "}\n"
            "\n"
            "")
        self.warning.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.warning.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.warning.setObjectName("warning")
        self.label_20 = QtWidgets.QLabel(self.warning)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 181, 23))
        self.label_20.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_20.setObjectName("label_20")
        self.widget = QtWidgets.QWidget(self.warning)
        self.widget.setGeometry(QtCore.QRect(0, 160, 471, 61))
        self.widget.setStyleSheet("QWidget{background-color: rgb(243, 243, 243);border-radius:12px;}\n"
                                  "\n"
                                  "")
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 16, 171, 31))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{border-radius:12px;\n"
                                        "    background-color: rgb(79, 209, 197);\n"
                                        "font: 700 10pt \"Microsoft YaHei UI\";}\n"
                                        "QPushButton#pushButton_3:hover{\n"
                                        "    \n"
                                        "    background-color: rgb(72, 191, 179);\n"
                                        "}\n"
                                        "")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 16, 171, 31))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{border-radius:12px;\n"
                                        "    \n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "font: 700 10pt \"Microsoft YaHei UI\";}\n"
                                        "QPushButton#pushButton_3:hover{\n"
                                        "    \n"
                                        "    background-color: rgb(238, 238, 238);\n"
                                        "}\n"
                                        "")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_21 = QtWidgets.QLabel(self.warning)
        self.label_21.setGeometry(QtCore.QRect(20, 50, 381, 41))
        self.label_21.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_21.setObjectName("label_21")
        self.Add = QtWidgets.QFrame(self.Task_ui)
        self.Add.setGeometry(QtCore.QRect(400, 60, 471, 261))
        self.Add.setStyleSheet(
            "QFrame#Add{border-radius:12px; border: 2px solid #e0e0e0; background-color: rgb(252, 252, 252);\n"
            "}\n"
            "\n"
            "")
        self.Add.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Add.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Add.setObjectName("Add")
        self.label_22 = QtWidgets.QLabel(self.Add)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 181, 23))
        self.label_22.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_22.setObjectName("label_22")
        self.widget_2 = QtWidgets.QWidget(self.Add)
        self.widget_2.setGeometry(QtCore.QRect(0, 200, 471, 61))
        self.widget_2.setStyleSheet("QWidget{background-color: rgb(243, 243, 243);border-radius:12px;}\n"
                                    "\n"
                                    "")
        self.widget_2.setObjectName("widget_2")
        self.OK_Add = QtWidgets.QPushButton(self.widget_2)
        self.OK_Add.setGeometry(QtCore.QRect(40, 16, 171, 31))
        self.OK_Add.setStyleSheet("QPushButton#OK_Add{border-radius:12px;\n"
                                  "    background-color: rgb(79, 209, 197);\n"
                                  "font: 700 10pt \"Microsoft YaHei UI\";}\n"
                                  "QPushButton#OK_Add:hover{\n"
                                  "    \n"
                                  "    background-color: rgb(72, 191, 179);\n"
                                  "}\n"
                                  "")
        self.OK_Add.setObjectName("OK_Add")
        self.Cancel_Add = QtWidgets.QPushButton(self.widget_2)
        self.Cancel_Add.setGeometry(QtCore.QRect(250, 16, 171, 31))
        self.Cancel_Add.setStyleSheet("QPushButton#Cancel_Add{border-radius:12px;\n"
                                      "    \n"
                                      "    background-color: rgb(255, 255, 255);\n"
                                      "font: 700 10pt \"Microsoft YaHei UI\";}\n"
                                      "QPushButton#Cancel_Add:hover{\n"
                                      "    \n"
                                      "    background-color: rgb(238, 238, 238);\n"
                                      "}\n"
                                      "")
        self.Cancel_Add.setObjectName("Cancel_Add")
        self.label_23 = QtWidgets.QLabel(self.Add)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 101, 41))
        self.label_23.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_23.setObjectName("label_23")
        self.lineEdit = QtWidgets.QLineEdit(self.Add)
        self.lineEdit.setGeometry(QtCore.QRect(90, 57, 351, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "    border: none;\n"
                                    "    border-bottom: 1px solid gray;  /* 默认灰色下划线 */\n"
                                    "    font: 700 9pt \"Microsoft YaHei UI\";\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit:focus {\n"
                                    "    border-bottom: 2px solid #45b7ac;  /* 获得焦点时绿色下划线 */\n"
                                    "}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_24 = QtWidgets.QLabel(self.Add)
        self.label_24.setGeometry(QtCore.QRect(10, 113, 101, 41))
        self.label_24.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_24.setObjectName("label_24")
        self.timeEdit = QtWidgets.QTimeEdit(self.Add)
        self.timeEdit.setGeometry(QtCore.QRect(90, 121, 351, 31))
        self.timeEdit.setStyleSheet("/* 修复 QTimeEdit 样式 - 保留功能按钮 */\n"
                                    "QTimeEdit {\n"
                                    "    border: none;\n"
                                    "    border-bottom: 1px solid gray;\n"
                                    "    font: 700 9pt \"Microsoft YaHei UI\";\n"
                                    "    background-color: transparent;  /* 保持背景透明 */\n"
                                    "}\n"
                                    "\n"
                                    "QTimeEdit:focus {\n"
                                    "    border-bottom: 2px solid #45b7ac;\n"
                                    "}\n"
                                    "\n"
                                    "/* 特别保护按钮区域 */\n"
                                    "QTimeEdit::up-button, \n"
                                    "QTimeEdit::down-button {\n"
                                    "    width: 15px;  /* 按钮宽度 */\n"
                                    "    subcontrol-origin: border;\n"
                                    "    subcontrol-position: right center;  /* 按钮位置 */\n"
                                    "}\n"
                                    "\n"
                                    "QTimeEdit::up-arrow, \n"
                                    "QTimeEdit::down-arrow {\n"
                                    "    width: 7px;  /* 箭头大小 */\n"
                                    "    height: 7px;\n"
                                    "}")
        self.timeEdit.setObjectName("timeEdit")

        self.add_shadows()



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Task"))
        self.label_19.setText(_translate("MainWindow", "All Task"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Today\'s Focus Sessions    "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Start or Remove this task?"))
        self.pushButton_2.setText(_translate("MainWindow", "Add Task"))
        self.label_20.setText(_translate("MainWindow", "Confirm Task Deletion"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.label_21.setText(_translate("MainWindow", "Are you sure to delete task,This action cannot be undone"))
        self.label_22.setText(_translate("MainWindow", "Add Task"))
        self.OK_Add.setText(_translate("MainWindow", "OK"))
        self.Cancel_Add.setText(_translate("MainWindow", "Cancel"))
        self.label_23.setText(_translate("MainWindow", "Task name:"))
        self.label_24.setText(_translate("MainWindow", "Focus time:"))


    def add_shadows(self):
        """为指定控件添加Windows 11风格的阴影"""
        # 需要添加阴影的控件列表
        shadow_widgets = [

            self.Add,
            self.warning,
            self.frame_6
        ]
        # 为每个控件添加阴影
        for widget in shadow_widgets:
            shadow = QtWidgets.QGraphicsDropShadowEffect(widget)
            shadow.setBlurRadius(20)
            shadow.setColor(QtGui.QColor(0, 0, 0, 60))
            shadow.setOffset(5, 5)
            widget.setGraphicsEffect(shadow)