# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Todo_ui.ui'
#
# Created by: PySide6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again. Do not edit this file unless you know what you are doing.
from PySide6.QtWidgets import QVBoxLayout

from Lock_ui import Ui_Lock_Window
from Setting_ui import Ui_Setting_Window
from Task_ui import Ui_Task_Window

from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCharts import QChart, QChartView, QPieSeries
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1534, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1741, 831))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color: rgb(248, 249, 250);\n"
"\n"
"\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 271, 771))
        self.frame_2.setStyleSheet("QFrame#frame_2{background-color: rgb(248, 249, 250);}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(20, 300, 218, 181))
        self.widget.setStyleSheet("QWidget#widget{\n"
"border-radius:15px;\n"
"    background-color: rgb(79, 209, 197);\n"
"}")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(18, 14, 35, 35))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:8px;")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(7, 7, 21, 21))
        self.label_3.setStyleSheet("background-color: rgb(79, 209, 197);\n"
"font: 700 14pt \"Microsoft YaHei UI\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(6, 80, 111, 21))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 12pt \"Microsoft YaHei UI\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(12, 100, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 290 10pt \"Microsoft YaHei UI\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(13, 130, 191, 41))
        self.pushButton.setStyleSheet("QPushButton#pushButton{background-color: rgb(255, 255, 255);border-radius:12px;\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton:hover{\n"
"    background-color: rgb(227, 227, 227);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(21, 87, 219, 201))
        self.listWidget.setStyleSheet("\n"
"QListWidget{\n"
"    background-color: rgb(248, 249, 250);\n"
"    color: rgb(182, 192, 206);\n"
"border-radius:5px;}\n"
"/* 近似圆角效果 */\n"
"QListWidget::item {\n"
"    padding: 13px;\n"
"    border-bottom: 1px solid #eee;\n"
"   magin:8px;\n"
"    background-color: rgb(248, 249, 250);\n"
"    /* 创建视觉上的圆角间隙 */\n"
"\n"
"}\n"
"QListWidget::item:hover {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #eee;\n"
"   \n"
"    background-color: rgb(255, 255, 255);\n"
"    margin: 4px;  /* 创建视觉上的圆角间隙 */\n"
"}\n"
"QListWidget::item:selected:hover{color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(32, 14, 198, 31))
        self.label.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(290, 10, 1241, 771))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Dashboard_ui = QtWidgets.QFrame(self.page)
        self.Dashboard_ui.setGeometry(QtCore.QRect(0, 0, 1241, 771))
        self.Dashboard_ui.setStyleSheet("QFrame#Dashboard_ui{background-color: rgb(248, 249, 250);\n"
"}\n"
"")
        self.Dashboard_ui.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Dashboard_ui.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Dashboard_ui.setObjectName("Dashboard_ui")
        self.label_6 = QtWidgets.QLabel(self.Dashboard_ui)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 198, 23))
        self.label_6.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";")
        self.label_6.setObjectName("label_6")
        self.widget_3 = QtWidgets.QWidget(self.Dashboard_ui)
        self.widget_3.setGeometry(QtCore.QRect(40, 70, 311, 71))
        self.widget_3.setStyleSheet("QWidget{background-color: rgb(255, 255, 255);border-radius:15px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 151, 23))
        self.label_7.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"color: rgb(160, 174, 192);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(10, 36, 141, 23))
        self.label_8.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.widget_4 = QtWidgets.QWidget(self.Dashboard_ui)
        self.widget_4.setGeometry(QtCore.QRect(440, 70, 331, 71))
        self.widget_4.setStyleSheet("QWidget{background-color: rgb(255, 255, 255);border-radius:15px;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(20, 36, 141, 23))
        self.label_9.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"")
        self.label_8.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 181, 23))
        self.label_10.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"color: rgb(160, 174, 192);")
        self.label_10.setObjectName("label_10")
        self.widget_5 = QtWidgets.QWidget(self.Dashboard_ui)
        self.widget_5.setGeometry(QtCore.QRect(880, 70, 321, 71))
        self.widget_5.setStyleSheet("QWidget{background-color: rgb(255, 255, 255);border-radius:15px;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setGeometry(QtCore.QRect(20, 36, 141, 23))
        self.label_11.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_5)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 191, 23))
        self.label_12.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"color: rgb(160, 174, 192);")
        self.label_12.setObjectName("label_12")
        self.frame_4 = QtWidgets.QFrame(self.Dashboard_ui)
        self.frame_4.setGeometry(QtCore.QRect(40, 160, 601, 251))
        self.frame_4.setStyleSheet("QFrame#frame_4{background-color: rgb(255, 255, 255);border-radius:12px;}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 251, 23))
        self.label_15.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_15.setObjectName("label_15")
        self.widget_6 = QtWidgets.QWidget(self.frame_4)
        self.widget_6.setGeometry(QtCore.QRect(30, 80, 201, 71))
        self.widget_6.setStyleSheet("QWidget{background-color: rgb(255, 255, 255);border-radius:15px;\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.label_13 = QtWidgets.QLabel(self.widget_6)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 151, 23))
        self.label_13.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"color: rgb(160, 174, 192);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget_6)
        self.label_14.setGeometry(QtCore.QRect(10, 36, 141, 23))
        self.label_14.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"")
        self.label_14.setObjectName("label_14")
        self.widget_8 = QtWidgets.QWidget(self.frame_4)
        self.widget_8.setGeometry(QtCore.QRect(370, 80, 201, 71))
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.label_16 = QtWidgets.QLabel(self.widget_8)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 151, 23))
        self.label_16.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"color: rgb(160, 174, 192);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_8)
        self.label_17.setGeometry(QtCore.QRect(10, 36, 141, 23))
        self.label_17.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
"")
        self.label_17.setObjectName("label_17")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 180, 191, 51))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{border-radius:12px;\n"
"    background-color: rgb(79, 209, 197);\n"
"font: 700 10pt \"Microsoft YaHei UI\";}\n"
"QPushButton#pushButton_2:hover{\n"
"    \n"
"    background-color: rgb(72, 191, 179);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_5 = QtWidgets.QFrame(self.Dashboard_ui)
        self.frame_5.setGeometry(QtCore.QRect(670, 160, 531, 251))
        self.frame_5.setStyleSheet("QFrame{background-color: rgb(255, 255, 255);border-radius:12px;}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 191, 23))
        self.label_18.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_18.setObjectName("label_18")
        self.widget_7 = QtWidgets.QWidget(self.frame_5)
        self.widget_7.setGeometry(QtCore.QRect(20, 40, 491, 191))
        self.widget_7.setStyleSheet("QWidget#widget_7{\n"
"border-radius:15px;\n"
"    background-color: rgb(79, 209, 197);\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setGeometry(QtCore.QRect(10, 10, 471, 171))
        self.widget_9.setStyleSheet("QWidget{background-color: rgb(255, 255, 255);border-radius:12px;}\n"
"")
        self.widget_9.setObjectName("widget_9")
        layout = QVBoxLayout(self.widget_9)
        layout.setContentsMargins(0, 0, 0, 0)

        self.frame_6 = QtWidgets.QFrame(self.Dashboard_ui)
        self.frame_6.setGeometry(QtCore.QRect(40, 440, 1161, 311))
        self.frame_6.setStyleSheet("QFrame{background-color: rgb(255, 255, 255);border-radius:12px;}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 181, 23))
        self.label_19.setStyleSheet("font: 700 14pt \"Microsoft YaHei\";")
        self.label_19.setObjectName("label_19")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 40, 1121, 241))
        self.tableWidget_2.setStyleSheet("/* 整体表格样式 */\n"
"QTableWidget {\n"
"     /* 浅灰色背景 */\n"
"    gridline-color: transparent;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #e5e5e5;\n"
"    border-radius: 4px;\n"
"    gridline-color: #e5e5e5;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    font-size: 12px;\n"
"    selection-background-color: #0078d4;  /* Windows 11选中色 */\n"
"    selection-color: white;\n"
"    outline: 0;  /* 移除选中时的虚线框 */\n"
"}\n"
"QTableView::item {\n"
"   \n"
"    border-right: none;  /* 隐藏竖线 */\n"
"}\n"
"/* 表头样式 */\n"
"QHeaderView::section {\n"
"    \n"
"    color: rgb(160, 174, 192);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    border: none;\n"
"    border-bottom: 1px solid #e5e5e5;\n"
"    font-weight: 500;  /* 中等粗细 */\n"
"    padding-left: 8px; \n"
"    \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QHeaderView::section:hover {\n"
"    background-color: #edebe9;\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QHeaderView::section:pressed {\n"
"    background-color: #e1dfdd;\n"
"}\n"
"\n"
"/* 行交替颜色 */\n"
"QTableWidget::item:alternate {\n"
"    background-color: #faf9f8;\n"
"}\n"
"\n"
"/* 单元格悬停效果 */\n"
"QTableWidget::item:hover {\n"
"    background-color: #f3f3f3;\n"
"}\n"
"\n"
"/* 滚动条样式 */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f3f3f3;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #c4c4c4;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #a0a0a0;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.tableWidget_2.setWordWrap(True)
        self.tableWidget_2.setCornerButtonEnabled(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()

        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(279)
        self.tableWidget_2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(39)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Notice = QtWidgets.QWidget(self.centralwidget)
        self.Notice.setGeometry(QtCore.QRect(830, 10, 401, 91))
        self.Notice.setStyleSheet("QWidget#Notice{;border-radius:15px;\n"
                                  "    \n"
                                  "    background-color: rgb(255, 255, 255);\n"
                                  "}\n"
                                  "")
        self.Notice.setObjectName("Notice")
        self.Title = QtWidgets.QLabel(self.Notice)
        self.Title.setGeometry(QtCore.QRect(15, 30, 151, 23))
        self.Title.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
                                 "color: rgb(0,0,0);")
        self.Title.setObjectName("Title")
        self.contect = QtWidgets.QLabel(self.Notice)
        self.contect.setGeometry(QtCore.QRect(15, 53, 221, 23))
        self.contect.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
                                   "color: rgb(222, 222, 222);")
        self.contect.setObjectName("contect")
        self.First_title = QtWidgets.QLabel(self.Notice)
        self.First_title.setGeometry(QtCore.QRect(16, 8, 221, 23))
        self.First_title.setStyleSheet("font: 700 12pt \"Microsoft YaHei\";\n"
                                   "color: rgb(222, 222, 222);")
        self.First_title.setObjectName("First_title")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        # --- 开始修改 ---
        self.task_ui = Ui_Task_Window()  # 1. 创建 UI '助手'类的实例
        self.task_ui.setupUi(self.page_2)  # 2. 调用 setupUi 将界面画在 self.page_2 上
        # --- 结束修改 ---
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        # --- 开始修改 ---
        self.lock_ui = Ui_Lock_Window()
        self.lock_ui.setupUi(self.page_3)
        # --- 结束修改 ---
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        # --- 开始修改 ---
        self.setting_ui = Ui_Setting_Window()
        self.setting_ui.setupUi(self.page_4)
        # --- 结束修改 ---

        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.add_shadows()



        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "?"))
        self.label_4.setText(_translate("MainWindow", "常看帮助？"))
        self.label_5.setText(_translate("MainWindow", "去官网看看"))
        self.pushButton.setText(_translate("MainWindow", "访问官网→"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Dashboard"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Task"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Focus Lock"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Setting"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.Title.setText(_translate("MainWindow", "title2"))
        self.contect.setText(_translate("MainWindow", "contect"))
        self.First_title.setText(_translate("MainWindow", "Title1"))
        self.label.setText(_translate("MainWindow", "Cheems Todo"))
        self.label_6.setText(_translate("MainWindow", "Dashboard"))
        self.label_7.setText(_translate("MainWindow", "总共专注次数"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "0 hour"))
        self.label_10.setText(_translate("MainWindow", "总共专注时间"))
        self.label_11.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "今日专注次数"))
        self.label_15.setText(_translate("MainWindow", "今日专注"))
        self.label_13.setText(_translate("MainWindow", "今日专注次数"))
        self.label_14.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "今日专注时间"))
        self.label_17.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "开始专注"))
        self.label_18.setText(_translate("MainWindow", "专注统计图（未上线）    "))
        self.label_19.setText(_translate("MainWindow", "今日任务"))
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名字"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "时间"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "今日已专注次数（在努力开发）QWQ "))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "开始专注？"))

    def add_shadows(self):
        """为指定控件添加Windows 11风格的阴影"""
        # 需要添加阴影的控件列表
        shadow_widgets = [
            self.widget_3,  # Dashboard 中的第一个卡片
            self.widget_4,  # Dashboard 中的第二个卡片
            self.widget_5,  # Dashboard 中的第三个卡片
            self.frame_4,  # Today's Focus 大卡片
            self.frame_5,  # Focus Distribution 大卡片
            self.frame_6,  # Today's Task 大卡片
            self.widget,
            self.Notice,# 左侧边栏的 Need help 卡片
        ]

        # 为每个控件添加阴影
        for widget in shadow_widgets:
            shadow = QtWidgets.QGraphicsDropShadowEffect(widget)
            shadow.setBlurRadius(20)  # 阴影模糊半径
            shadow.setColor(QtGui.QColor(0, 0, 0, 30))  # 阴影颜色和透明度
            shadow.setOffset(0, 2)  # 阴影偏移量
            widget.setGraphicsEffect(shadow)

            # 确保控件有适当的边距，防止阴影被裁剪
            #widget.setAttribute(QtCore.Qt.WA_TranslucentBackground)
            if hasattr(widget, 'setContentsMargins'):
                widget.setContentsMargins(10, 10, 10, 10)